package com.lz.myboot.common.model;

public class Resource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.resource
     *
     * @mbggenerated
     */
    private String resource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.menuName
     *
     * @mbggenerated
     */
    private String menuname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.id
     *
     * @return the value of resource.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.id
     *
     * @param id the value for resource.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.resource
     *
     * @return the value of resource.resource
     *
     * @mbggenerated
     */
    public String getResource() {
        return resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.resource
     *
     * @param resource the value for resource.resource
     *
     * @mbggenerated
     */
    public void setResource(String resource) {
        this.resource = resource == null ? null : resource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.menuName
     *
     * @return the value of resource.menuName
     *
     * @mbggenerated
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.menuName
     *
     * @param menuname the value for resource.menuName
     *
     * @mbggenerated
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }
}